# Auto-assign configuration for pull requests
addReviewers: true
addAssignees: false

reviewers:
  - eduardkakosyan  # Repository owner

numberOfReviewers: 1

# Skip auto-assignment for draft PRs
skipDraftPR: true

# Skip auto-assignment for WIP PRs
skipKeywords:
  - wip
  - WIP
  - draft
  - DRAFT