name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check if running in act
      id: check-env
      run: |
        if [ "${{ env.ACT }}" = "true" ]; then
          echo "running_in_act=true" >> $GITHUB_OUTPUT
          echo "⚠️ Running in act (local simulation)"
        else
          echo "running_in_act=false" >> $GITHUB_OUTPUT
          echo "✅ Running on real GitHub Actions"
        fi
      
    - name: Setup Xcode (GitHub Actions only)
      if: steps.check-env.outputs.running_in_act != 'true'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Mock Xcode setup (act simulation)
      if: steps.check-env.outputs.running_in_act == 'true'
      run: |
        echo "🔧 Simulating Xcode setup for local testing"
        echo "In a real environment, this would set up Xcode"
        # Create mock commands to prevent command not found errors
        mkdir -p /usr/local/bin
        echo '#!/bin/bash' > /usr/local/bin/xcodebuild
        echo 'echo "Mock xcodebuild called with: $@"' >> /usr/local/bin/xcodebuild
        echo 'echo "In act simulation - tests would run here"' >> /usr/local/bin/xcodebuild
        chmod +x /usr/local/bin/xcodebuild
        
    - name: Cache Swift Package Manager
      if: steps.check-env.outputs.running_in_act != 'true'
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/org.swift.swiftpm/
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages/
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Install Dependencies
      if: steps.check-env.outputs.running_in_act != 'true'
      run: |
        if [ -f "Package.swift" ]; then
          swift package resolve
        fi
        
    - name: Run SwiftLint (if available)
      continue-on-error: true
      run: |
        if command -v swiftlint &> /dev/null; then
          swiftlint
        else
          echo "SwiftLint not installed, skipping"
        fi
        
    - name: Validate Swift Files (act simulation)
      if: steps.check-env.outputs.running_in_act == 'true'
      run: |
        echo "🔍 Validating Swift project structure..."
        echo "Swift files found:"
        find . -name "*.swift" -type f | head -10
        echo ""
        echo "📱 iOS App structure:"
        ls -la FinSync/
        echo ""
        echo "🧪 Test files:"
        find . -name "*Tests.swift" -type f
        echo ""
        echo "✅ Project validation complete (act simulation)"
        
    - name: Run Tests (GitHub Actions)
      if: steps.check-env.outputs.running_in_act != 'true'
      run: |
        xcodebuild test \
          -scheme FinSync \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -enableCodeCoverage YES \
          -derivedDataPath DerivedData
          
    - name: Simulate Tests (act)
      if: steps.check-env.outputs.running_in_act == 'true'
      run: |
        echo "🧪 Simulating test execution..."
        echo "In a real environment, this would run:"
        echo "  xcodebuild test -scheme FinSync -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'"
        echo ""
        echo "Test files that would be executed:"
        find . -name "*Tests.swift" -exec basename {} \;
        echo "✅ Tests simulated successfully"
          
    - name: Generate Code Coverage Report
      if: steps.check-env.outputs.running_in_act != 'true'
      run: |
        xcrun xccov view DerivedData/Logs/Test/*.xcresult --report --only-targets
        
    - name: Build for Release (GitHub Actions)
      if: steps.check-env.outputs.running_in_act != 'true'
      run: |
        xcodebuild build \
          -scheme FinSync \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Simulate Build (act)
      if: steps.check-env.outputs.running_in_act == 'true'
      run: |
        echo "🔨 Simulating release build..."
        echo "In a real environment, this would run:"
        echo "  xcodebuild build -scheme FinSync -configuration Release"
        echo "✅ Build simulation complete"
          
    - name: Archive build artifacts
      if: success() && steps.check-env.outputs.running_in_act != 'true'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          DerivedData/Build/Products/
          DerivedData/Logs/
        retention-days: 7
        
    - name: Simulation Summary
      if: steps.check-env.outputs.running_in_act == 'true'
      run: |
        echo "📋 Act Simulation Summary:"
        echo "=========================="
        echo "✅ Project structure validated"
        echo "✅ Swift files found and checked"
        echo "✅ Test files identified"
        echo "✅ Build process simulated"
        echo ""
        echo "💡 To run real tests:"
        echo "   • Use GitHub Actions with macOS runner"
        echo "   • Or run locally: xcodebuild test -scheme FinSync"