name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          chore
        scopes: |
          home
          receipts
          charts
          analytics
          core
          tests
          ci
          expo
          deps
          config
          
    - name: Check PR size
      uses: noqcks/xarrays@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        max_lines_changed: 500
        
    - name: Require tests for new features
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'FinSync/src/**/*.{ts,tsx}'
            - 'FinSync/components/**/*.{ts,tsx}'
            - 'FinSync/app/**/*.{ts,tsx}'
          tests:
            - 'FinSync/__tests__/**/*.{ts,tsx}'
            - 'FinSync/**/*.test.{ts,tsx}'
            - 'FinSync/**/*.spec.{ts,tsx}'
            
    - name: Comment if tests missing
      if: steps.changes.outputs.src == 'true' && steps.changes.outputs.tests == 'false'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ **Missing Tests**: This PR modifies source code but doesn\'t include corresponding test changes. Please add appropriate unit tests.'
          })
          
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: FinSync/package-lock.json
        
    - name: Install dependencies
      working-directory: ./FinSync
      run: npm ci
      
    - name: Check TypeScript
      working-directory: ./FinSync
      run: npm run typecheck || echo "TypeScript errors detected but allowing PR to continue"
      
    - name: Check ESLint
      working-directory: ./FinSync
      run: npm run lint || echo "ESLint errors detected but allowing PR to continue"
      
    - name: Check formatting
      working-directory: ./FinSync
      run: npm run format:check || echo "Formatting issues detected but allowing PR to continue"
      
    - name: Run tests
      working-directory: ./FinSync
      run: npm test -- --passWithNoTests
      
  auto-assign-reviewers:
    name: Auto-assign Reviewers  
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    
    steps:
    - name: Auto-assign reviewer
      uses: kentaro-m/auto-assign-action@v1.2.5
      with:
        configuration-path: '.github/auto-assign.yml'